### ISSUE TITLE
화면 개선 - 가사 불러오기 전 로딩서클 보여주기

### ISSUE THREAD

**Issue by leeyi1203** [ProjectInTheClass/GasaOK#25]
# 가사 불러오기 전 로딩서클 보여주기

* API 호출 시 가사를 띄워주기까지 어느 정도의 시간이 걸리므로 로딩서클 추가하여 UI 개선

**Comment by dahae0320** [comment]
가사 저작권 문제로 가사 API 사용을 하지 않음! 그래서 이 이슈 닫슴다
