### ISSUE TITLE
[UI] 검색 화면에서 취소 버튼 클릭 시 scope bar 숨김 처리

### ISSUE THREAD

**Issue by leeyi1203** [ProjectInTheClass/GasaOK#47]
## Feature Issue
검색 화면에서 취소 버튼 클릭 시 scope bar가 사라지지 않고 남아있어 UI가 깔끔하지 않음

## ToDo
취소 버튼 클릭 시 scope bar 숨김 처리

**Comment by dahae0320** [comment]
이제 필요없는 이슈여서 닫습니다. (기능에서 제외)
