### ISSUE TITLE
[BugFix] 노래 검색 결과 데이터 누락

### ISSUE THREAD

**Issue by leeyi1203** [ProjectInTheClass/GasaOK#65]
### 문제상황
노래 검색 시 결과 누락 발생
(ex 코요태 - 순정, 비몽 등 / 이외에도 한 단어 당 여러 개 누락됨)

## 해결 방안
- [x] 오류 메세지 전체 출력으로 문제점 파악
- [x] 문제 해결

**Comment by dahae0320** [comment]
코드 리팩토링 과정에서 수정되었음.
